#!/usr/bin/env bash

##
## Review is a CLI for automating code review with stash.
##

set -e

bin=$(dirname "$0")
bin=$(cd "$bin">/dev/null; pwd)

if [ -L "$bin/review" ]; then
  # its a symlink, so set bin to where the real file is
  bin=$(dirname $(readlink "$bin/review"))
  bin=$(cd "$bin">/dev/null; pwd)
fi

SUBCMD_DIR="$bin/subcmds"

info() {
  echo "[INFO] : $@"
}

warn() {
  echo "[WARN] : $@" 1>&2
}

fatal() {
  echo "[FATAL] : $@" 1>&2
  exit 1
}

parse_config() {
  ruby <<EOF
require 'yaml'

def to_bash(prefix, data)
  data.each do |key, value|
    if value.class == Hash then
      to_bash("#{key}_", value)
    elsif value.class == Array then
      puts "#{prefix}#{key}=(#{value.join(' ')})"
    else
      puts "#{prefix}#{key}=\"#{value}\""
    end
  end
end

data = YAML.load(File.read('.reviewrc'))

to_bash("", data)
EOF
}

commands() {
  for cmd in $(ls $SUBCMD_DIR/*.sh | sed "s;$SUBCMD_DIR/;;g" | sed 's;.sh;;g')
  do
    # "  $cmd   $summary"
    printf "  %-15s%s\n" "$cmd" "$(cat $SUBCMD_DIR/$cmd.summary 2> /dev/null)"
  done
}

usage() {
  cat <<EOF 1>&2
Usage: review COMMAND [arg...]

Commands:
$(commands)
EOF
  exit 1
}

main() {
  if [ $# -lt 1 ]; then
    usage
  fi

  local cmd="$1"; shift

  if [ -e "$SUBCMD_DIR/$cmd.sh" ]; then
    # eval is evil?  Is there a cleaner way to do this with the YAML config?
    eval $(parse_config)
    . "$SUBCMD_DIR/$cmd.sh" 
    run "$@"
  else
    warn "Unknown command: $cmd"
    usage
  fi
}

main "$@"

